<?php
declare(strict_types=1);
require_once __DIR__ . '/functions.php';

$page = (string)($_GET['page'] ?? 'home');

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    try {
        if ($page === 'register') {
            $name = post('name');
            $email = strtolower(post('email'));
            $password = post('password');
            $role = post('role');

            if (strlen($name) < 2 || !filter_var($email, FILTER_VALIDATE_EMAIL) || strlen($password) < 8 || !in_array($role, ['parent', 'student'], true)) {
                throw new RuntimeException('Enter a valid name, email, role, and a password of at least 8 characters.');
            }

            $profile = $role === 'student'
                ? [post('bio'), post('subjects'), post('qualifications'), max(0, (int) post('experience_years')), post('hourly_rate') !== '' ? (float) post('hourly_rate') : null, post('availability'), post('teaching_mode') ?: 'both', post('location'), post('languages')]
                : ['', '', '', 0, null, '', 'both', post('location'), post('languages')];

            if ($role === 'student' && (strlen($profile[0]) < 20 || $profile[1] === '' || $profile[2] === '' || $profile[5] === '' || $profile[7] === '')) {
                throw new RuntimeException('Tutor/Student accounts must include a bio, subjects, qualifications, availability, and location.');
            }

            $statement = db()->prepare('INSERT INTO users(name,email,password,role,bio,subjects,qualifications,experience_years,hourly_rate,availability,teaching_mode,location,languages) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');
            $statement->execute([$name, $email, password_hash($password, PASSWORD_DEFAULT), $role, ...$profile]);
            flash('success', 'Account created. You can now sign in.');
            redirect('login');
        }
        if ($page === 'login') {
            $submittedEmail = strtolower(post('email'));
            $submittedPassword = post('password');
            $statement = db()->prepare('SELECT * FROM users WHERE email = ?');
            $statement->execute([$submittedEmail]);
            $account = $statement->fetch();

            if (!$account || !password_verify($submittedPassword, $account['password'])) {
                throw new RuntimeException('The email or password is incorrect.');
            }
            if ($account['is_suspended']) {
                throw new RuntimeException('This account has been suspended.');
            }

            session_regenerate_id(true);
            $_SESSION['user'] = ['id' => (int) $account['id'], 'name' => $account['name'], 'email' => $account['email'], 'role' => $account['role']];
            flash('success', 'Welcome back, ' . $account['name'] . '!');
            redirect('dashboard');
        }
        if ($page === 'logout') { require_login(); $_SESSION=[]; session_destroy(); header('Location: index.php'); exit; }
        if ($page === 'profile') {
            $u=require_login(); $fields=['name','bio','subjects','qualifications','availability','location','languages','education_level','learning_goals']; $values=[]; foreach($fields as $f)$values[]=post($f);
            $rate=post('hourly_rate')!==''?(float)post('hourly_rate'):null; $years=max(0,(int)post('experience_years')); $mode=in_array(post('teaching_mode'),['online','in_person','both'],true)?post('teaching_mode'):'both';
            $s=db()->prepare('UPDATE users SET name=?,bio=?,subjects=?,qualifications=?,availability=?,location=?,languages=?,education_level=?,learning_goals=?,hourly_rate=?,experience_years=?,teaching_mode=? WHERE id=?'); $s->execute([...$values,$rate,$years,$mode,$u['id']]);
            $_SESSION['user']['name']=$values[0]; flash('success','Your profile has been updated.'); redirect('profile');
        }
        if ($page === 'job_form') {
            $u=require_role('parent','admin'); $id=(int)($_GET['id']??0); $subjectList=implode(', ',array_unique(array_filter(array_map('trim',explode(',',post('subject')))))); $data=[post('title'),post('tutee_name'),(int)post('age'),$subjectList,post('education_level'),post('description'),post('schedule'),(float)post('payment'),post('location'),post('teaching_mode')];
            if(strlen($data[0])<5 || !$data[3] || strlen($data[5])<10 || $data[7]<=0) throw new RuntimeException('Complete all required job details and enter a valid budget.');
            if($id){$s=db()->prepare('UPDATE tutoring_jobs SET title=?,tutee_name=?,age=?,subject=?,education_level=?,description=?,schedule=?,payment=?,location=?,teaching_mode=? WHERE id=? AND user_id=?');$s->execute([...$data,$id,$u['id']]);flash('success','Job updated.');}
            else{$s=db()->prepare('INSERT INTO tutoring_jobs(title,tutee_name,age,subject,education_level,description,schedule,payment,location,teaching_mode,user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->execute([...$data,$u['id']]);flash('success','Your tutoring job is now live.');}
            redirect('my_jobs');
        }
        if ($page === 'apply') {
            $u=require_role('student'); $job=(int)post('job_id'); $s=db()->prepare("SELECT * FROM tutoring_jobs WHERE id=? AND status='open'");$s->execute([$job]);$j=$s->fetch();if(!$j)throw new RuntimeException('This job is no longer accepting applications.');
            $s=db()->prepare('INSERT INTO applications(job_id,student_id,cover_note) VALUES(?,?,?)');$s->execute([$job,$u['id'],post('cover_note')]);notify((int)$j['user_id'],$u['name'].' applied to “'.$j['title'].'”.',$job);flash('success','Application sent successfully.');redirect('applications');
        }
        if ($page === 'save_job') { $u=require_role('student');$job=(int)post('job_id');$sql=db_driver()==='sqlite'?'INSERT OR IGNORE INTO saved_jobs(user_id,job_id) VALUES(?,?)':(config_value('DATABASE_URL')!==''?'INSERT INTO saved_jobs(user_id,job_id) VALUES(?,?) ON CONFLICT DO NOTHING':'INSERT IGNORE INTO saved_jobs(user_id,job_id) VALUES(?,?)');$s=db()->prepare($sql);$s->execute([$u['id'],$job]);flash('success','Job saved.');redirect('jobs'); }
        if ($page === 'application_action') {
            $u=require_login();$id=(int)post('application_id');$action=post('action');
            $s=db()->prepare('SELECT a.*,j.user_id,j.title FROM applications a JOIN tutoring_jobs j ON j.id=a.job_id WHERE a.id=?');$s->execute([$id]);$a=$s->fetch();if(!$a)throw new RuntimeException('Application not found.');
            if($action==='withdraw' && (int)$a['student_id']===$u['id']){$s=db()->prepare("UPDATE applications SET status='withdrawn' WHERE id=? AND status IN ('pending','shortlisted')");$s->execute([$id]);flash('success','Application withdrawn.');redirect('applications');}
            if((int)$a['user_id']!==$u['id'] && $u['role']!=='admin')throw new RuntimeException('You cannot manage this application.');
            if(!in_array($action,['shortlisted','accepted','rejected'],true))throw new RuntimeException('Invalid application action.');
            db()->beginTransaction();$s=db()->prepare('UPDATE applications SET status=? WHERE id=?');$s->execute([$action,$id]);
            if($action==='accepted'){$s=db()->prepare("UPDATE tutoring_jobs SET status='assigned' WHERE id=?");$s->execute([$a['job_id']]);$s=db()->prepare("UPDATE applications SET status='rejected' WHERE job_id=? AND id<>? AND status IN ('pending','shortlisted')");$s->execute([$a['job_id'],$id]);$welcome="Your application has been accepted. Let’s use this private chat to arrange the first class.";$s=db()->prepare('INSERT INTO messages(sender_id,receiver_id,job_id,body) VALUES(?,?,?,?)');$s->execute([$u['id'],$a['student_id'],$a['job_id'],$welcome]);}
            db()->commit();$notice=$action==='accepted'?'Your application for “'.$a['title'].'” was accepted. A private conversation is ready in Messages so you can arrange the class.':'Your application for “'.$a['title'].'” was '.$action.'.';notify((int)$a['student_id'],$notice,(int)$a['job_id']);flash('success',$action==='accepted'?'Tutor approved. A private conversation has been created in Messages.':'Application marked '.$action.'.');redirect('my_jobs',['id'=>$a['job_id']]);
        }
        if ($page === 'job_status') {
            $u=require_login();$id=(int)post('job_id');$status=post('status');if(!in_array($status,['in_progress','completed','cancelled'],true))throw new RuntimeException('Invalid job status.');
            $s=db()->prepare('SELECT * FROM tutoring_jobs WHERE id=?');$s->execute([$id]);$j=$s->fetch();if(!$j || ((int)$j['user_id']!==$u['id'] && $u['role']!=='admin'))throw new RuntimeException('You cannot update this job.');
            $s=db()->prepare('UPDATE tutoring_jobs SET status=? WHERE id=?');$s->execute([$status,$id]);$s=db()->prepare("SELECT student_id FROM applications WHERE job_id=? AND status='accepted'");$s->execute([$id]);if($sid=$s->fetchColumn())notify((int)$sid,'“'.$j['title'].'” is now '.str_replace('_',' ',$status).'.',$id);flash('success','Job status updated.');redirect('my_jobs',['id'=>$id]);
        }
        if ($page === 'send_message') {
            $u=require_login();$to=(int)post('receiver_id');$body=post('body');$job=(int)post('job_id')?:null;if($to===$u['id']||strlen($body)<1||strlen($body)>3000)throw new RuntimeException('Enter a valid message.');
            $s=db()->prepare('SELECT id FROM users WHERE id=? AND is_suspended=0');$s->execute([$to]);if(!$s->fetch())throw new RuntimeException('Recipient not found.');$s=db()->prepare('INSERT INTO messages(sender_id,receiver_id,job_id,body) VALUES(?,?,?,?)');$s->execute([$u['id'],$to,$job,$body]);notify($to,$u['name'].' sent you a message.',$job);redirect('messages',['with'=>$to,'job'=>$job]);
        }
        if ($page === 'review') {
            $u=require_login();$job=(int)post('job_id');$rating=(int)post('rating');if($rating<1||$rating>5)throw new RuntimeException('Choose a rating from 1 to 5.');
            $s=db()->prepare("SELECT j.user_id,a.student_id FROM tutoring_jobs j JOIN applications a ON a.job_id=j.id AND a.status='accepted' WHERE j.id=? AND j.status='completed'");$s->execute([$job]);$x=$s->fetch();if(!$x)throw new RuntimeException('Only completed jobs can be reviewed.');$reviewee=$u['id']==(int)$x['user_id']?(int)$x['student_id']:(int)$x['user_id'];if(!in_array($u['id'],[(int)$x['user_id'],(int)$x['student_id']],true))throw new RuntimeException('You were not part of this job.');
            $s=db()->prepare('INSERT INTO reviews(job_id,reviewer_id,reviewee_id,rating,comment) VALUES(?,?,?,?,?)');$s->execute([$job,$u['id'],$reviewee,$rating,post('comment')]);notify($reviewee,$u['name'].' left you a review.',$job);flash('success','Thanks for sharing your review.');redirect('dashboard');
        }
        if ($page === 'report') { $u=require_login();$job=(int)post('job_id');if(strlen(post('reason'))<5)throw new RuntimeException('Tell us why you are reporting this listing.');$s=db()->prepare('INSERT INTO reports(reporter_id,job_id,reason) VALUES(?,?,?)');$s->execute([$u['id'],$job,post('reason')]);flash('success','Report submitted for admin review.');redirect('job',['id'=>$job]); }
        if ($page === 'notifications') { $u=require_login();$s=db()->prepare('UPDATE notifications SET is_read=1 WHERE user_id=?');$s->execute([$u['id']]);redirect('notifications'); }
        if ($page === 'admin_action') {
            require_role('admin');$action=post('action');$id=(int)post('id');
            if($action==='toggle_suspend'){$s=db()->prepare('UPDATE users SET is_suspended=1-is_suspended WHERE id=? AND role<>\'admin\'');$s->execute([$id]);}
            elseif($action==='verify'){$s=db()->prepare('UPDATE users SET is_verified=1 WHERE id=?');$s->execute([$id]);}
            elseif($action==='resolve'){$s=db()->prepare("UPDATE reports SET status='resolved' WHERE id=?");$s->execute([$id]);}
            elseif($action==='delete_user'){$s=db()->prepare("DELETE FROM users WHERE id=? AND role<>'admin'");$s->execute([$id]);if(!$s->rowCount())throw new RuntimeException('Administrators cannot be deleted.');}
            else throw new RuntimeException('Invalid admin action.');flash('success','Admin action completed.');redirect('admin');
        }
        if ($page === 'admin_user') {
            require_role('admin');$id=(int)post('id');$role=post('role');if(!in_array($role,['parent','student'],true))throw new RuntimeException('Choose Parent or Tutor/Student.');
            $name=post('name');$email=strtolower(post('email'));if(strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter a valid name and email address.');
            $s=db()->prepare("UPDATE users SET name=?,email=?,role=?,bio=?,subjects=?,qualifications=?,experience_years=?,hourly_rate=?,availability=?,teaching_mode=?,location=?,languages=?,is_verified=?,is_suspended=? WHERE id=? AND role<>'admin'");
            $s->execute([$name,$email,$role,post('bio'),post('subjects'),post('qualifications'),max(0,(int)post('experience_years')),post('hourly_rate')!==''?(float)post('hourly_rate'):null,post('availability'),post('teaching_mode')?:'both',post('location'),post('languages'),isset($_POST['is_verified'])?1:0,isset($_POST['is_suspended'])?1:0,$id]);
            if(!$s->rowCount()){$check=db()->prepare("SELECT id FROM users WHERE id=? AND role<>'admin'");$check->execute([$id]);if(!$check->fetch())throw new RuntimeException('This account cannot be edited.');}
            flash('success','User account updated.');redirect('admin');
        }
    } catch (PDOException $ex) {
        if(db()->inTransaction())db()->rollBack();
        $message=$ex->getCode()==='23000'?'That record already exists or conflicts with existing data.':'The database could not complete the request.'; flash('error',$message); redirect($page);
    } catch (RuntimeException $ex) { if(db()->inTransaction())db()->rollBack();flash('error',$ex->getMessage());redirect($page); }
}

if ($page==='home') {
    $stats=['tutors'=>(int)db()->query("SELECT COUNT(*) FROM users WHERE role='student'")->fetchColumn(),'jobs'=>(int)db()->query("SELECT COUNT(*) FROM tutoring_jobs WHERE status='open'")->fetchColumn(),'matches'=>(int)db()->query("SELECT COUNT(*) FROM applications WHERE status='accepted'")->fetchColumn()];
    render_header('Find the right tutor'); ?>
    <section class="hero"><div><span class="eyebrow">Learn with confidence</span><h1>The right tutor can change everything.</h1><p>Connect with trusted local and online tutors, manage applications, and turn learning goals into real progress.</p><div class="actions"><a class="btn" href="<?=url('jobs')?>">Explore tutoring jobs</a><a class="btn btn-ghost" href="<?=url('register')?>">Create an account</a></div></div><div class="hero-card"><div class="avatar large">✓</div><h3>Trusted connections</h3><p>Profiles, structured applications, secure messaging, and verified reviews—all in one place.</p><div class="mini-stats"><b><?=$stats['tutors']?> tutors</b><b><?=$stats['jobs']?> open jobs</b><b><?=$stats['matches']?> matches</b></div></div></section>
    <section><div class="section-heading"><span class="eyebrow">How it works</span><h2>A simpler path to better learning</h2></div><div class="features"><article><span>01</span><h3>Create your profile</h3><p>Share subjects, experience, learning goals, location, and availability.</p></article><article><span>02</span><h3>Discover your match</h3><p>Search and filter opportunities, then apply or shortlist with confidence.</p></article><article><span>03</span><h3>Learn and grow</h3><p>Message, manage progress, complete the job, and leave a trusted review.</p></article></div></section>
    <?php render_footer(); exit;
}

if ($page==='register'||$page==='login') { if(logged_in())redirect('dashboard');render_header($page==='login'?'Welcome back':'Join TutorLink'); ?>
    <section class="auth-card"><div><span class="eyebrow"><?=$page==='login'?'Welcome back':'Start learning better'?></span><h1><?=$page==='login'?'Sign in to your account':'Create your free account'?></h1><p><?=$page==='login'?'Continue managing your tutoring journey.':'Join as a Tutor/Student or Parent and find the right learning connection.'?></p></div><form method="post" class="panel"><?=csrf_field()?><?php if($page==='register'):?><label>Full name<input name="name" required minlength="2" autocomplete="name"></label><?php endif?><label>Email address<input type="email" name="email" required autocomplete="email"></label><label>Password<input type="password" name="password" required minlength="8" autocomplete="<?=$page==='login'?'current-password':'new-password'?>"></label><?php if($page==='register'):?><label>I am joining as<select name="role"><option value="student">Tutor/Student</option><option value="parent">Parent</option></select></label><?php endif?><?php if($page==='register') render_tutor_registration_fields(); ?><button class="btn" type="submit"><?=$page==='login'?'Sign in':'Create account'?></button><p class="muted"><?=$page==='login'?'New here? <a href="'.url('register').'">Create an account</a>':'Already registered? <a href="'.url('login').'">Sign in</a>'?></p></form></section>
    <?php render_footer();exit;
}

if ($page==='dashboard') { $u=require_login();
    if($u['role']==='parent'){$s=db()->prepare('SELECT COUNT(*) FROM tutoring_jobs WHERE user_id=?');$s->execute([$u['id']]);$a=(int)$s->fetchColumn();$s=db()->prepare('SELECT COUNT(*) FROM applications a JOIN tutoring_jobs j ON j.id=a.job_id WHERE j.user_id=?');$s->execute([$u['id']]);$b=(int)$s->fetchColumn();$primary=['My job posts',$a,'Applications received',$b,'Post a job',url('job_form')];}
    elseif($u['role']==='student'){$s=db()->prepare('SELECT COUNT(*) FROM applications WHERE student_id=?');$s->execute([$u['id']]);$a=(int)$s->fetchColumn();$s=db()->prepare('SELECT COUNT(*) FROM saved_jobs WHERE user_id=?');$s->execute([$u['id']]);$b=(int)$s->fetchColumn();$primary=['My applications',$a,'Saved jobs',$b,'Find a job',url('jobs')];}
    else{$a=(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn();$b=(int)db()->query('SELECT COUNT(*) FROM reports WHERE status=\'open\'')->fetchColumn();$primary=['Members',$a,'Open reports',$b,'Open admin',url('admin')];}
    $s=db()->prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 5');$s->execute([$u['id']]);$notes=$s->fetchAll();render_header('Dashboard'); ?>
    <section class="page-heading"><div><span class="eyebrow">Your workspace</span><h1>Hello, <?=e(explode(' ',$u['name'])[0])?>.</h1><p>Here is what is happening with your tutoring journey.</p></div><a class="btn" href="<?=$primary[5]?>"><?=$primary[4]?></a></section><div class="stats-grid"><article><span><?=$primary[0]?></span><strong><?=$primary[1]?></strong></article><article><span><?=$primary[2]?></span><strong><?=$primary[3]?></strong></article><article><span>Account type</span><strong class="capitalize"><?=e($u['role'])?></strong></article></div><section class="panel"><div class="panel-heading"><h2>Recent notifications</h2><a href="<?=url('notifications')?>">View all</a></div><?php if($notes):foreach($notes as $n):?><div class="list-row"><div class="icon">●</div><div><b><?=e($n['message'])?></b><small><?=e(date('M j, Y g:i a',strtotime($n['created_at'])))?></small></div></div><?php endforeach;else:?><div class="empty compact">No updates yet.</div><?php endif?></section>
    <?php render_footer();exit;
}

if ($page==='jobs') {
    $q=trim((string)($_GET['q']??''));$subject=trim((string)($_GET['subject']??''));$mode=trim((string)($_GET['mode']??''));$sort=(string)($_GET['sort']??'newest');$order=$sort==='price_low'?'j.payment ASC':($sort==='price_high'?'j.payment DESC':'j.created_at DESC');
    $sql="SELECT j.*,u.name posted_by FROM tutoring_jobs j JOIN users u ON u.id=j.user_id WHERE j.status='open'";$args=[];if($q!==''){$sql.=' AND (j.title LIKE ? OR j.description LIKE ? OR j.location LIKE ? OR j.subject LIKE ?)';$like="%$q%";$args=[$like,$like,$like,$like];}if($subject!==''){$sql.=' AND j.subject LIKE ?';$args[]='%'.$subject.'%';}if(in_array($mode,['online','in_person','both'],true)){$sql.=' AND j.teaching_mode=?';$args[]=$mode;}$sql.=" ORDER BY $order";$s=db()->prepare($sql);$s->execute($args);$jobs=$s->fetchAll();$rawSubjects=db()->query("SELECT subject FROM tutoring_jobs WHERE status='open' ORDER BY subject")->fetchAll();$subjectNames=[];foreach($rawSubjects as $row){foreach(explode(',',$row['subject']) as $name){$name=trim($name);if($name!=='')$subjectNames[$name]=true;}}$subjects=array_map(static fn($name)=>['subject'=>$name],array_keys($subjectNames));render_header('Find tutoring jobs'); ?>
    <section class="page-heading"><div><span class="eyebrow">Opportunities</span><h1>Find work that fits you.</h1><p>Search by subject, location, teaching mode, or budget.</p></div><?php if(user()&&user()['role']==='parent'):?><a class="btn" href="<?=url('job_form')?>">Post a job</a><?php endif?></section><form class="filter panel" method="get"><input type="hidden" name="page" value="jobs"><label>Search<input name="q" value="<?=e($q)?>" placeholder="Subject, keyword, location"></label><label>Subject<select name="subject"><option value="">All subjects</option><?php foreach($subjects as $x):?><option <?=$subject===$x['subject']?'selected':''?>><?=e($x['subject'])?></option><?php endforeach?></select></label><label>Teaching mode<select name="mode"><option value="">Any mode</option><option value="online" <?=$mode==='online'?'selected':''?>>Online</option><option value="in_person" <?=$mode==='in_person'?'selected':''?>>In person</option><option value="both" <?=$mode==='both'?'selected':''?>>Both</option></select></label><label>Sort<select name="sort"><option value="newest">Newest</option><option value="price_high" <?=$sort==='price_high'?'selected':''?>>Highest budget</option><option value="price_low" <?=$sort==='price_low'?'selected':''?>>Lowest budget</option></select></label><button class="btn">Search</button></form><div class="job-grid"><?php foreach($jobs as $j):?><article class="job-card"><div class="job-top"><span class="subject"><?=e($j['subject'])?></span><?=badge($j['teaching_mode'])?></div><h2><a href="<?=url('job',['id'=>$j['id']])?>"><?=e($j['title'])?></a></h2><p><?=e(mb_strimwidth($j['description'],0,150,'…'))?></p><div class="meta"><span>⌖ <?=e($j['location']?:'Flexible')?></span><span>◷ <?=e($j['schedule'])?></span></div><div class="job-bottom"><div><b>ETB <?=number_format((float)$j['payment'])?></b><small>per session</small></div><a class="btn btn-small" href="<?=url('job',['id'=>$j['id']])?>">View details</a></div></article><?php endforeach?></div><?php if(!$jobs):?><div class="empty"><h2>No jobs match those filters</h2><p>Try removing a filter or searching with a broader term.</p></div><?php endif?>
    <?php render_footer();exit;
}

if ($page==='job') { $id=(int)($_GET['id']??0);$s=db()->prepare('SELECT j.*,u.name posted_by,u.is_verified FROM tutoring_jobs j JOIN users u ON u.id=j.user_id WHERE j.id=?');$s->execute([$id]);$j=$s->fetch();if(!$j)render_error('That job could not be found.');render_header($j['title']);?>
    <section class="detail-layout"><article class="panel detail"><div class="job-top"><span class="subject"><?=e($j['subject'])?></span><?=badge($j['status'])?></div><h1><?=e($j['title'])?></h1><p class="lead"><?=nl2br(e($j['description']))?></p><h3>About the learner</h3><div class="detail-grid"><div><small>Learner</small><b><?=e($j['tutee_name'])?><?= $j['age']?' · age '.e($j['age']):''?></b></div><div><small>Education level</small><b><?=e($j['education_level'])?></b></div><div><small>Schedule</small><b><?=e($j['schedule'])?></b></div><div><small>Teaching mode</small><b><?=e(ucwords(str_replace('_',' ',$j['teaching_mode'])))?></b></div><div><small>Location</small><b><?=e($j['location']?:'Flexible')?></b></div><div><small>Budget</small><b>ETB <?=number_format((float)$j['payment'])?> / session</b></div></div></article><aside class="panel sticky"><div class="avatar"><?=e(strtoupper(substr($j['posted_by'],0,1)))?></div><h3><?=e($j['posted_by'])?> <?=$j['is_verified']?'✓':''?></h3><p class="muted">Posted <?=e(date('M j, Y',strtotime($j['created_at'])))?></p><?php if(!logged_in()):?><a class="btn block" href="<?=url('login')?>">Sign in to apply</a><?php elseif(user()['role']==='student'&&$j['status']==='open'):?><form method="post" action="<?=url('apply')?>"><?=csrf_field()?><input type="hidden" name="job_id" value="<?=$j['id']?>"><label>Application note<textarea name="cover_note" required placeholder="Introduce yourself and explain why you are a good match."></textarea></label><button class="btn block">Apply now</button></form><form method="post" action="<?=url('save_job')?>"><?=csrf_field()?><input type="hidden" name="job_id" value="<?=$j['id']?>"><button class="btn btn-secondary block">Save job</button></form><?php endif?><?php if(logged_in()&&user()['id']!==(int)$j['user_id']):?><details><summary>Report listing</summary><form method="post" action="<?=url('report')?>"><?=csrf_field()?><input type="hidden" name="job_id" value="<?=$j['id']?>"><textarea name="reason" required placeholder="What should our team review?"></textarea><button class="btn btn-danger btn-small">Submit report</button></form></details><?php endif?></aside></section>
    <?php render_footer();exit;
}

if ($page==='job_form') { $u=require_role('parent','admin');$id=(int)($_GET['id']??0);$j=['title'=>'','tutee_name'=>'','age'=>'','subject'=>'','education_level'=>'','description'=>'','schedule'=>'','payment'=>'','location'=>'','teaching_mode'=>'both'];if($id){$s=db()->prepare('SELECT * FROM tutoring_jobs WHERE id=? AND user_id=?');$s->execute([$id,$u['id']]);$j=$s->fetch()?:render_error('Job not found.');}render_header($id?'Edit job':'Post a tutoring job');?>
    <section class="form-page"><div><span class="eyebrow">For parents</span><h1><?=$id?'Update your job':'Find the perfect tutor'?></h1><p>Clear details help qualified tutors understand the learner and submit better applications.</p></div><form method="post" class="panel form-grid"><?=csrf_field()?><label class="wide">Job title<input name="title" value="<?=e($j['title'])?>" required></label><label>Learner name<input name="tutee_name" value="<?=e($j['tutee_name'])?>" required></label><label>Age<input type="number" min="3" max="100" name="age" value="<?=e($j['age'])?>"></label><label>Subjects (separate with commas)<input name="subject" placeholder="Mathematics, Physics" value="<?=e($j['subject'])?>" required></label><label>Education level<input name="education_level" value="<?=e($j['education_level'])?>" required></label><label>Session budget (ETB)<input type="number" min="1" name="payment" value="<?=e($j['payment'])?>" required></label><label>Teaching mode<select name="teaching_mode"><option value="online" <?=$j['teaching_mode']==='online'?'selected':''?>>Online</option><option value="in_person" <?=$j['teaching_mode']==='in_person'?'selected':''?>>In person</option><option value="both" <?=$j['teaching_mode']==='both'?'selected':''?>>Both</option></select></label><label>Location<input name="location" value="<?=e($j['location'])?>" placeholder="City or neighbourhood"></label><label>Preferred schedule<input name="schedule" value="<?=e($j['schedule'])?>" required></label><label class="wide">What support is needed?<textarea name="description" required><?=e($j['description'])?></textarea></label><button class="btn wide"><?=$id?'Save changes':'Publish job'?></button></form></section>
    <?php render_footer();exit;
}

if ($page==='my_jobs') { $u=require_role('parent','admin');$s=db()->prepare('SELECT j.*,COUNT(a.id) applicants FROM tutoring_jobs j LEFT JOIN applications a ON a.job_id=j.id WHERE j.user_id=? GROUP BY j.id ORDER BY j.created_at DESC');$s->execute([$u['id']]);$jobs=$s->fetchAll();render_header('My jobs');?>
    <section class="page-heading"><div><span class="eyebrow">Manage listings</span><h1>My tutoring jobs</h1></div><a class="btn" href="<?=url('job_form')?>">Post new job</a></section><?php foreach($jobs as $j):?><article class="panel manage-job"><div><div class="job-top"><?=badge($j['status'])?><span class="subject"><?=e($j['subject'])?></span></div><h2><?=e($j['title'])?></h2><p><?=e($j['applicants'])?> applicants · ETB <?=number_format((float)$j['payment'])?> / session</p><div class="actions"><a class="btn btn-small btn-secondary" href="<?=url('job_form',['id'=>$j['id']])?>">Edit</a><?php if(in_array($j['status'],['assigned','in_progress'],true)):?><form method="post" action="<?=url('job_status')?>"><?=csrf_field()?><input type="hidden" name="job_id" value="<?=$j['id']?>"><input type="hidden" name="status" value="<?=$j['status']==='assigned'?'in_progress':'completed'?>"><button class="btn btn-small"><?=$j['status']==='assigned'?'Start job':'Mark complete'?></button></form><?php endif?></div></div><div class="applicants"><?php $a=db()->prepare('SELECT a.*,u.name,u.subjects,u.experience_years FROM applications a JOIN users u ON u.id=a.student_id WHERE a.job_id=? ORDER BY a.created_at');$a->execute([$j['id']]);$apps=$a->fetchAll();if($apps):foreach($apps as $x):?><div class="applicant"><div class="avatar"><?=e(strtoupper(substr($x['name'],0,1)))?></div><div><b><?=e($x['name'])?></b><small><?=e($x['subjects']?:'Profile not completed')?> · <?=e($x['experience_years'])?> yrs</small><p><?=e($x['cover_note'])?></p></div><div><?=badge($x['status'])?><?php if(in_array($x['status'],['pending','shortlisted'],true)):?><form method="post" action="<?=url('application_action')?>"><?=csrf_field()?><input type="hidden" name="application_id" value="<?=$x['id']?>"><div class="button-stack"><button name="action" value="accepted" class="btn btn-small">Accept</button><button name="action" value="shortlisted" class="btn btn-small btn-secondary">Shortlist</button><button name="action" value="rejected" class="link-button danger">Reject</button></div></form><?php endif?></div></div><?php endforeach;else:?><p class="muted">No applications yet.</p><?php endif?></div></article><?php endforeach?><?php if(!$jobs):?><div class="empty"><h2>You have not posted a job yet</h2><a class="btn" href="<?=url('job_form')?>">Create your first listing</a></div><?php endif?>
    <?php render_footer();exit;
}

if ($page==='applications') { $u=require_role('student');$s=db()->prepare('SELECT a.*,j.title,j.subject,j.payment,j.status job_status,u.name parent_name FROM applications a JOIN tutoring_jobs j ON j.id=a.job_id JOIN users u ON u.id=j.user_id WHERE a.student_id=? ORDER BY a.created_at DESC');$s->execute([$u['id']]);$apps=$s->fetchAll();render_header('My applications');?>
    <section class="page-heading"><div><span class="eyebrow">Your progress</span><h1>Applications</h1></div><a class="btn" href="<?=url('jobs')?>">Find more jobs</a></section><div class="panel table-wrap"><table><thead><tr><th>Opportunity</th><th>Parent</th><th>Budget</th><th>Applied</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($apps as $a):?><tr><td><a href="<?=url('job',['id'=>$a['job_id']])?>"><b><?=e($a['title'])?></b></a><small><?=e($a['subject'])?></small></td><td><?=e($a['parent_name'])?></td><td>ETB <?=number_format((float)$a['payment'])?></td><td><?=e(date('M j',strtotime($a['created_at'])))?></td><td><?=badge($a['status'])?></td><td><?php if(in_array($a['status'],['pending','shortlisted'],true)):?><form method="post" action="<?=url('application_action')?>"><?=csrf_field()?><input type="hidden" name="application_id" value="<?=$a['id']?>"><button name="action" value="withdraw" class="link-button danger" data-confirm="Withdraw this application?">Withdraw</button></form><?php endif?></td></tr><?php endforeach?></tbody></table><?php if(!$apps):?><div class="empty compact">You have not applied to any jobs yet.</div><?php endif?></div>
    <?php render_footer();exit;
}

if ($page==='tutors') { require_role('parent','admin');$q=trim((string)($_GET['q']??''));$sql="SELECT u.*,COALESCE(AVG(r.rating),0) rating,COUNT(r.id) review_count FROM users u LEFT JOIN reviews r ON r.reviewee_id=u.id WHERE u.role='student' AND u.is_suspended=0";$args=[];if($q!==''){$sql.=' AND (u.name LIKE ? OR u.subjects LIKE ? OR u.location LIKE ? OR u.qualifications LIKE ?)';$like="%$q%";$args=[$like,$like,$like,$like];}$sql.=' GROUP BY u.id ORDER BY u.is_verified DESC,rating DESC,u.experience_years DESC';$s=db()->prepare($sql);$s->execute($args);$tutors=$s->fetchAll();render_header('Tutor profiles');?>
    <section class="page-heading"><div><span class="eyebrow">Tutor/Student directory</span><h1>Know your applicants better.</h1><p>Review qualifications, experience, availability, languages, location, rates, and teaching approach.</p></div></section><form method="get" class="panel filter"><input type="hidden" name="page" value="tutors"><label>Search tutor profiles<input name="q" value="<?=e($q)?>" placeholder="Name, subject, qualification, or location"></label><button class="btn">Search</button></form><div class="job-grid"><?php foreach($tutors as $t):?><article class="panel tutor-card"><div class="profile-head"><div class="avatar large"><?=e(strtoupper(substr($t['name'],0,1)))?></div><div><h2><?=e($t['name'])?> <?=$t['is_verified']?'✓':''?></h2><p>★ <?=number_format((float)$t['rating'],1)?> · <?=e($t['review_count'])?> reviews</p></div></div><p><?=e($t['bio']?:'This tutor has not added a bio yet.')?></p><div class="detail-grid"><div><small>Subjects</small><b><?=e($t['subjects']?:'Not provided')?></b></div><div><small>Qualifications</small><b><?=e($t['qualifications']?:'Not provided')?></b></div><div><small>Experience</small><b><?=e($t['experience_years'])?> years</b></div><div><small>Rate</small><b><?=$t['hourly_rate']!==null?'ETB '.number_format((float)$t['hourly_rate']).' / session':'Not provided'?></b></div><div><small>Availability</small><b><?=e($t['availability']?:'Not provided')?></b></div><div><small>Teaching mode</small><b><?=e(ucwords(str_replace('_',' ',$t['teaching_mode'])))?></b></div><div><small>Location</small><b><?=e($t['location']?:'Not provided')?></b></div><div><small>Languages</small><b><?=e($t['languages']?:'Not provided')?></b></div></div><a class="btn block" href="<?=url('messages',['with'=>$t['id']])?>">Message <?=e(explode(' ',$t['name'])[0])?></a></article><?php endforeach?></div><?php if(!$tutors):?><div class="empty"><h2>No Know your applicants better. match your search.</h2></div><?php endif?>
    <?php render_footer();exit;
}

if ($page==='profile') { $u=require_login();$s=db()->prepare('SELECT u.*,COALESCE(AVG(r.rating),0) rating,COUNT(r.id) review_count FROM users u LEFT JOIN reviews r ON r.reviewee_id=u.id WHERE u.id=? GROUP BY u.id');$s->execute([$u['id']]);$p=$s->fetch();render_header('My profile');?>
    <section class="profile-head"><div class="avatar huge"><?=e(strtoupper(substr($p['name'],0,1)))?></div><div><span class="eyebrow"><?=e($p['role'])?> profile <?=$p['is_verified']?'· Verified':''?></span><h1><?=e($p['name'])?></h1><p>★ <?=number_format((float)$p['rating'],1)?> from <?=e($p['review_count'])?> reviews · Member since <?=e(date('M Y',strtotime($p['created_at'])))?></p></div></section><form method="post" class="panel form-grid"><?=csrf_field()?><label>Full name<input name="name" value="<?=e($p['name'])?>" required></label><label>Location<input name="location" value="<?=e($p['location'])?>"></label><label>Subjects<input name="subjects" value="<?=e($p['subjects'])?>" placeholder="Math, Physics, English"></label><label>Qualifications<input name="qualifications" value="<?=e($p['qualifications'])?>"></label><label>Years of experience<input type="number" min="0" name="experience_years" value="<?=e($p['experience_years'])?>"></label><label>Hourly rate (ETB)<input type="number" min="0" name="hourly_rate" value="<?=e($p['hourly_rate'])?>"></label><label>Teaching mode<select name="teaching_mode"><option value="online" <?=$p['teaching_mode']==='online'?'selected':''?>>Online</option><option value="in_person" <?=$p['teaching_mode']==='in_person'?'selected':''?>>In person</option><option value="both" <?=$p['teaching_mode']==='both'?'selected':''?>>Both</option></select></label><label>Availability<input name="availability" value="<?=e($p['availability'])?>"></label><label>Languages<input name="languages" value="<?=e($p['languages'])?>"></label><label>Education level<input name="education_level" value="<?=e($p['education_level'])?>"></label><label class="wide">Bio<textarea name="bio"><?=e($p['bio'])?></textarea></label><label class="wide">Learning goals<textarea name="learning_goals"><?=e($p['learning_goals'])?></textarea></label><button class="btn wide">Save profile</button></form>
    <?php render_footer();exit;
}

if ($page==='notifications') { $u=require_login();$s=db()->prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100');$s->execute([$u['id']]);$items=$s->fetchAll();render_header('Notifications');?>
    <section class="page-heading"><div><span class="eyebrow">Stay updated</span><h1>Notifications</h1></div><form method="post"><?=csrf_field()?><button class="btn btn-secondary">Mark all as read</button></form></section><div class="panel"><?php foreach($items as $n):?><div class="list-row <?=$n['is_read']?'':'unread'?>"><div class="icon">●</div><div><b><?=e($n['message'])?></b><small><?=e(date('M j, Y g:i a',strtotime($n['created_at'])))?></small></div><?php if($n['job_id']):?><a href="<?=url('job',['id'=>$n['job_id']])?>">View</a><?php endif?></div><?php endforeach?><?php if(!$items):?><div class="empty compact">You are all caught up.</div><?php endif?></div>
    <?php render_footer();exit;
}

if ($page==='messages') { $u=require_login();$s=db()->prepare('SELECT u.id,u.name,MAX(m.created_at) last_at FROM messages m JOIN users u ON u.id=CASE WHEN m.sender_id=? THEN m.receiver_id ELSE m.sender_id END WHERE m.sender_id=? OR m.receiver_id=? GROUP BY u.id,u.name ORDER BY last_at DESC');$s->execute([$u['id'],$u['id'],$u['id']]);$people=$s->fetchAll();$with=(int)($_GET['with']??($people[0]['id']??0));$thread=[];$peer=null;if($with){$s=db()->prepare('SELECT id,name FROM users WHERE id=?');$s->execute([$with]);$peer=$s->fetch();$s=db()->prepare('SELECT * FROM messages WHERE (sender_id=? AND receiver_id=?) OR (sender_id=? AND receiver_id=?) ORDER BY created_at');$s->execute([$u['id'],$with,$with,$u['id']]);$thread=$s->fetchAll();$s=db()->prepare('UPDATE messages SET is_read=1 WHERE sender_id=? AND receiver_id=?');$s->execute([$with,$u['id']]);}render_header('Messages');?>
    <section class="page-heading"><div><span class="eyebrow">Conversations</span><h1>Messages</h1></div></section><div class="messages-layout"><aside class="panel conversation-list"><?php foreach($people as $x):?><a class="conversation <?=$with===$x['id']?'active':''?>" href="<?=url('messages',['with'=>$x['id']])?>"><div class="avatar"><?=e(strtoupper(substr($x['name'],0,1)))?></div><div><b><?=e($x['name'])?></b><small><?=e(date('M j, g:i a',strtotime($x['last_at'])))?></small></div></a><?php endforeach?><?php if(!$people):?><p class="muted">No conversations yet. Accepted applicants and job owners can start a conversation from their workflow.</p><?php endif?></aside><section class="panel chat"><?php if($peer):?><div class="chat-head"><h2><?=e($peer['name'])?></h2></div><div class="chat-body"><?php foreach($thread as $m):?><div class="bubble <?=$m['sender_id']==$u['id']?'mine':''?>"><p><?=nl2br(e($m['body']))?></p><small><?=e(date('M j, g:i a',strtotime($m['created_at'])))?></small></div><?php endforeach?></div><form method="post" action="<?=url('send_message')?>" class="chat-form"><?=csrf_field()?><input type="hidden" name="receiver_id" value="<?=$with?>"><input type="hidden" name="job_id" value="<?=e($_GET['job']??'')?>"><textarea name="body" required placeholder="Write a message…"></textarea><button class="btn">Send</button></form><?php else:?><div class="empty"><h2>Select a conversation</h2></div><?php endif?></section></div>
    <?php render_footer();exit;
}

if ($page==='admin_user') { require_role('admin');$id=(int)($_GET['id']??0);$s=db()->prepare("SELECT * FROM users WHERE id=? AND role<>'admin'");$s->execute([$id]);$member=$s->fetch();if(!$member)render_error('This user cannot be edited.');render_header('Edit user');?>
    <section class="page-heading"><div><span class="eyebrow">User management</span><h1>Edit <?=e($member['name'])?></h1><p>Update account access and profile information.</p></div><a class="btn btn-secondary" href="<?=url('admin')?>">Back to admin</a></section><form method="post" class="panel form-grid"><?=csrf_field()?><input type="hidden" name="id" value="<?=$member['id']?>"><label>Full name<input name="name" value="<?=e($member['name'])?>" required></label><label>Email address<input type="email" name="email" value="<?=e($member['email'])?>" required></label><label>Account role<select name="role"><option value="student" <?=$member['role']==='student'?'selected':''?>>Tutor/Student</option><option value="parent" <?=$member['role']==='parent'?'selected':''?>>Parent</option></select></label><label>Teaching mode<select name="teaching_mode"><option value="both" <?=$member['teaching_mode']==='both'?'selected':''?>>Online and in person</option><option value="online" <?=$member['teaching_mode']==='online'?'selected':''?>>Online</option><option value="in_person" <?=$member['teaching_mode']==='in_person'?'selected':''?>>In person</option></select></label><label>Subjects<input name="subjects" value="<?=e($member['subjects'])?>"></label><label>Qualifications<input name="qualifications" value="<?=e($member['qualifications'])?>"></label><label>Experience in years<input type="number" min="0" name="experience_years" value="<?=e($member['experience_years'])?>"></label><label>Rate per session (ETB)<input type="number" min="0" name="hourly_rate" value="<?=e($member['hourly_rate'])?>"></label><label>Availability<input name="availability" value="<?=e($member['availability'])?>"></label><label>Location<input name="location" value="<?=e($member['location'])?>"></label><label>Languages<input name="languages" value="<?=e($member['languages'])?>"></label><label class="check"><input type="checkbox" name="is_verified" value="1" <?=$member['is_verified']?'checked':''?>> Verified account</label><label class="check"><input type="checkbox" name="is_suspended" value="1" <?=$member['is_suspended']?'checked':''?>> Suspended account</label><label class="wide">Biography<textarea name="bio"><?=e($member['bio'])?></textarea></label><button class="btn wide">Save user</button></form>
    <?php render_footer();exit;
}

if ($page==='admin') { require_role('admin');$users=db()->query('SELECT id,name,email,role,is_verified,is_suspended,created_at FROM users ORDER BY created_at DESC LIMIT 50')->fetchAll();$reports=db()->query('SELECT r.*,u.name reporter,j.title FROM reports r JOIN users u ON u.id=r.reporter_id LEFT JOIN tutoring_jobs j ON j.id=r.job_id ORDER BY r.status,r.created_at DESC')->fetchAll();$counts=['users'=>(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn(),'jobs'=>(int)db()->query('SELECT COUNT(*) FROM tutoring_jobs')->fetchColumn(),'reports'=>(int)db()->query("SELECT COUNT(*) FROM reports WHERE status='open'")->fetchColumn()];render_header('Admin');?>
    <section class="page-heading"><div><span class="eyebrow">Platform operations</span><h1>Admin dashboard</h1></div></section><div class="stats-grid"><article><span>Members</span><strong><?=$counts['users']?></strong></article><article><span>Total jobs</span><strong><?=$counts['jobs']?></strong></article><article><span>Open reports</span><strong><?=$counts['reports']?></strong></article></div><section class="panel table-wrap"><div class="panel-heading"><h2>Members</h2></div><table><thead><tr><th>Name</th><th>Role</th><th>Joined</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($users as $x):?><tr><td><b><?=e($x['name'])?></b><small><?=e($x['email'])?></small></td><td><?=e($x['role'])?></td><td><?=e(date('M j, Y',strtotime($x['created_at'])))?></td><td><?=$x['is_suspended']?badge('suspended'):badge('active')?> <?=$x['is_verified']?badge('verified'):''?></td><td><form method="post" action="<?=url('admin_action')?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$x['id']?>"><?php if($x['role']!=='admin'):?><button name="action" value="toggle_suspend" class="link-button"><?=$x['is_suspended']?'Restore':'Suspend'?></button><?php if(!$x['is_verified']):?><button name="action" value="verify" class="link-button">Verify</button><?php endif?><?php endif?></form></td></tr><?php endforeach?></tbody></table></section><section class="panel"><div class="panel-heading"><h2>Reports</h2></div><?php foreach($reports as $r):?><div class="list-row"><div><b><?=e($r['title']?:'Removed listing')?></b><p><?=e($r['reason'])?></p><small>Reported by <?=e($r['reporter'])?></small></div><?=badge($r['status'])?><?php if($r['status']==='open'):?><form method="post" action="<?=url('admin_action')?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><button name="action" value="resolve" class="btn btn-small">Resolve</button></form><?php endif?></div><?php endforeach?><?php if(!$reports):?><div class="empty compact">No reports submitted.</div><?php endif?></section>
    <?php render_footer();exit;
}

render_error('The requested page does not exist.');




